site_name: bareASGI-jinja2
site_description: Jinja2 support for bareASGI
site_dir: docs

docs_dir: documentation

repo_name: rob-blackbourn/bareASGI-jinja2
repo_url: https://github.com/rob-blackbourn/bareASGI-jinja2
edit_uri: ""

theme:
    name: "material"
    logo: images/peach.svg
    favicon: images/favicon.ico

nav:
    - index.md
    - User Guide:
          - user-guide/installation.md
          - user-guide/usage.md
    - API:
          - bareasgi_jinja2: api/bareasgi_jinja2.md

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
    - jetblack_markdown.autodoc:
          class_from_init: true
          ignore_dunder: true
          ignore_private: true
          ignore_all: false
          ignore_inherited: false
          follow_module_tree: false
          prefer_docstring: true
          template_folder: templates
    - toc:
          permalink: true

extra_css:
    - css/custom.css
